NXP-23722: Use session.createEntry(Collections.singletonMap(k,v))
nuxeo/nuxeo-audit-storage-directory pull request #2
Opened 2017-11-30 16:42 UTC by egiuly-nuxeo

See https://github.com/nuxeo/nuxeo/pull/1494

2017-11-30 16:43 UTC, nuxeojenkins commented
[View issue in JIRA](https://jira.nuxeo.com/browse/NXP-23722)

2017-11-30 21:17 UTC, efge requested changes
Use "Prevent directory sessions from modifying their parameters" as a commit message, instead of a low-level technical description

2017-11-30 21:30 UTC, efge approved these changes

2017-11-30 21:30 UTC, efge commented
👍

2017-12-01 09:07 UTC, funshodavid commented
:+1:

2017-12-01 18:28 UTC, merged